datasources:
  default:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    driverClassName: oracle.jdbc.OracleDriver
    username: PayrollService
    password: PayrollServicePassword

flyway:
  datasources:
    default:
      url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
      username: PayrollService
      password: PayrollServicePassword
      baseline-on-migrate: true

  oracle:
    sysdba: true